run "helpers_aws_config_recording_source_inventory" {
  command = plan

  module {
    source = "../../../tests/tofu/module_contract"
  }

  variables {
    module_path = "."
    expected_literals = [
      "resource \"aws_config_configuration_recorder\" \"this\"",
      "resource \"aws_config_delivery_channel\" \"this\"",
      "resource \"aws_config_configuration_recorder_status\" \"this\"",
      "resource \"aws_iam_role\" \"config\"",
      "resource \"aws_s3_bucket\" \"config_delivery\"",
      "resource \"aws_s3_bucket_ownership_controls\" \"config_delivery\"",
      "resource \"aws_s3_bucket_versioning\" \"config_delivery\"",
      "resource \"aws_s3_bucket_server_side_encryption_configuration\" \"config_delivery\"",
      "resource \"aws_s3_bucket_public_access_block\" \"config_delivery\"",
      "resource \"aws_s3_bucket_lifecycle_configuration\" \"config_delivery\"",
      "resource \"aws_s3_bucket_policy\" \"config_delivery\"",
      "resource \"aws_sqs_queue\" \"config_events_dlq\"",
      "resource \"aws_sqs_queue\" \"config_events\"",
      "resource \"aws_sqs_queue_policy\" \"config_events\"",
      "resource \"aws_s3_bucket_notification\" \"config_events\"",
      "data \"aws_caller_identity\" \"current\"",
      "data \"aws_iam_policy_document\" \"config_delivery_bucket\"",
      "data \"aws_iam_policy_document\" \"config_events\"",
      "identifiers = [\"config.amazonaws.com\"]",
      "identifiers = [\"s3.amazonaws.com\"]",
      "\"s3:GetBucketAcl\"",
      "\"s3:ListBucket\"",
      "actions   = [\"s3:PutObject\"]",
      "actions   = [\"sqs:SendMessage\"]",
      "resources = [\"$${aws_s3_bucket.config_delivery[0].arn}/AWSLogs/$${data.aws_caller_identity.current.account_id}/Config/*\"]",
      "values   = [\"arn:$${data.aws_partition.current.partition}:config:$${var.aws_region}:$${data.aws_caller_identity.current.account_id}:*\"]",
      "values   = [aws_s3_bucket.config_delivery[0].arn]",
      "variable = \"AWS:SourceAccount\"",
      "variable = \"s3:x-amz-acl\"",
      "variable = \"aws:SourceArn\"",
      "variable = \"aws:SourceAccount\"",
      "variable = \"aws:SecureTransport\"",
      "values   = [\"bucket-owner-full-control\"]",
      "values   = [\"false\"]",
      "sqs_managed_sse_enabled   = true",
      "message_retention_seconds = 1209600",
      "visibility_timeout_seconds = 300",
      "deadLetterTargetArn = aws_sqs_queue.config_events_dlq[0].arn",
      "maxReceiveCount     = 5",
      "events        = [\"s3:ObjectCreated:*\"]",
      "filter_suffix = \".json.gz\"",
      "depends_on = [aws_sqs_queue_policy.config_events]",
      join("\n", [
        "  statement {",
        "    sid    = \"AWSConfigBucketPermissionsCheck\"",
        "    effect = \"Allow\"",
        "    actions = [",
        "      \"s3:GetBucketAcl\",",
        "      \"s3:ListBucket\",",
        "    ]",
        "    resources = [aws_s3_bucket.config_delivery[0].arn]",
        "",
        "    principals {",
        "      type        = \"Service\"",
        "      identifiers = [\"config.amazonaws.com\"]",
        "    }",
        "",
        "    condition {",
        "      test     = \"StringEquals\"",
        "      variable = \"AWS:SourceAccount\"",
        "      values   = [data.aws_caller_identity.current.account_id]",
        "    }",
        "",
        "    condition {",
        "      test     = \"ArnLike\"",
        "      variable = \"AWS:SourceArn\"",
        "      values   = [\"arn:$${data.aws_partition.current.partition}:config:$${var.aws_region}:$${data.aws_caller_identity.current.account_id}:*\"]",
        "    }",
        "  }",
      ]),
      join("\n", [
        "  statement {",
        "    sid       = \"AWSConfigBucketDelivery\"",
        "    effect    = \"Allow\"",
        "    actions   = [\"s3:PutObject\"]",
        "    resources = [\"$${aws_s3_bucket.config_delivery[0].arn}/AWSLogs/$${data.aws_caller_identity.current.account_id}/Config/*\"]",
        "",
        "    principals {",
        "      type        = \"Service\"",
        "      identifiers = [\"config.amazonaws.com\"]",
        "    }",
        "",
        "    condition {",
        "      test     = \"StringEquals\"",
        "      variable = \"AWS:SourceAccount\"",
        "      values   = [data.aws_caller_identity.current.account_id]",
        "    }",
        "",
        "    condition {",
        "      test     = \"StringEquals\"",
        "      variable = \"s3:x-amz-acl\"",
        "      values   = [\"bucket-owner-full-control\"]",
        "    }",
        "",
        "    condition {",
        "      test     = \"ArnLike\"",
        "      variable = \"AWS:SourceArn\"",
        "      values   = [\"arn:$${data.aws_partition.current.partition}:config:$${var.aws_region}:$${data.aws_caller_identity.current.account_id}:*\"]",
        "    }",
        "  }",
      ]),
      join("\n", [
        "  statement {",
        "    sid    = \"AllowConfigBucketNotifications\"",
        "    effect = \"Allow\"",
        "",
        "    principals {",
        "      type        = \"Service\"",
        "      identifiers = [\"s3.amazonaws.com\"]",
        "    }",
        "",
        "    actions   = [\"sqs:SendMessage\"]",
        "    resources = [aws_sqs_queue.config_events[0].arn]",
        "",
        "    condition {",
        "      test     = \"ArnEquals\"",
        "      variable = \"aws:SourceArn\"",
        "      values   = [aws_s3_bucket.config_delivery[0].arn]",
        "    }",
        "",
        "    condition {",
        "      test     = \"StringEquals\"",
        "      variable = \"aws:SourceAccount\"",
        "      values   = [data.aws_caller_identity.current.account_id]",
        "    }",
        "  }",
      ]),
      "var.recorded_resource_types",
      "provider \"aws\"",
    ]
  }

  assert {
    condition     = length(output.missing_expected_literals) == 0
    error_message = "Source inventory is missing expected Terraform blocks: ${join(", ", output.missing_expected_literals)}"
  }

  assert {
    condition     = output.expected_literal_count == 47
    error_message = "Source inventory must keep 47 AWS Config, managed S3, and Splunk-ready SQS Terraform blocks and exact policy contracts pinned."
  }
}
