---
env: <ENVIRONMENT_NAME>                       # e.g., "prod"
default_aws_region: <DEFAULT_AWS_REGION>      # e.g., "eu-west-1"
runner_group_name_suffix: <RUNNER_GROUP_SUFFIX>   # e.g., "cicd-forge"
aws_account_id: <AWS_ACCOUNT_ID>              # e.g., "123456789012"
