run "platform_ec2_deployment_interface_contract" {
  command = plan

  module {
    source = "../../../tests/tofu/module_interface_contract"
  }

  variables {
    module_path = "."
    expected_input_variables = [
      "aws_region",
      "network_configs",
      "runner_configs",
      "tenant_configs",
    ]
    expected_output_values = [
      "ec2_runners_ami_name_map",
      "ec2_runners_arn_map",
      "ec2_runners_labels_map",
      "event_bus_name",
      "subnet_cidr_blocks",
      "webhook_endpoint",
    ]
    expected_interface_literals = [
      "variable \"aws_region\"",
      "type        = string",
      "description = \"Assuming single region for now.\"",
      "variable \"network_configs\"",
      "type = object({",
      "vpc_id            = string",
      "subnet_ids        = list(string)",
      "lambda_vpc_id     = string",
      "lambda_subnet_ids = list(string)",
      "variable \"runner_configs\"",
      "env                       = string",
      "prefix                    = string",
      "ghes_url                  = string",
      "log_level                 = string",
      "logging_retention_in_days = string",
      "github_app = object({",
      "key_base64     = string",
      "id             = string",
      "webhook_secret = string",
      "runner_iam_role_managed_policy_arns = list(string)",
      "runner_specs = map(object({",
      "tags = optional(map(string), {})",
      "runner = object({",
      "os                     = string",
      "architecture           = string",
      "disable_default_labels = optional(bool, null)",
      "extra_labels           = optional(list(string), null)",
      "group_name             = optional(string, null)",
      "name_prefix            = optional(string, null)",
      "run_as_root            = optional(bool, null)",
      "run_as                 = optional(string, null)",
      "auto_update_disabled   = optional(bool, null)",
      "orchestration_provider = object({",
      "webhook = optional(object({",
      "boot_time_in_minutes = optional(number, null)",
      "ephemeral            = optional(bool, null)",
      "jit_config_enabled   = optional(bool, null)",
      "maximum_count        = number",
      "hooks = optional(object({",
      "job_started   = optional(string, null)",
      "job_completed = optional(string, null)",
      "iam = optional(object({",
      "role = optional(object({",
      "managed_policy_arns          = optional(map(string), null)",
      "additional_trust_policy_json = optional(string, null)",
      "path                         = optional(string, null)",
      "permissions_boundary         = optional(string, null)",
      "github = optional(object({",
      "organization_runners = optional(bool, false)",
      "lambda = optional(object({",
      "runtime            = optional(string, null)",
      "architecture       = optional(string, null)",
      "security_group_ids = optional(list(string), null)",
      "role = optional(object({",
      "memory_size                    = optional(number, null)",
      "timeout                        = optional(number, null)",
      "queue = optional(object({",
      "delay_webhook_event            = optional(number, null)",
      "job_queue_retention_in_seconds = optional(number, null)",
      "visibility_timeout_seconds     = optional(number, null)",
      "event_source_mapping = optional(object({",
      "batch_size                         = optional(number, null)",
      "maximum_batching_window_in_seconds = optional(number, null)",
      "redrive_build_queue = optional(object({",
      "enabled         = optional(bool, null)",
      "maxReceiveCount = optional(number, null)",
      "scale = optional(object({",
      "up = optional(object({",
      "reserved_concurrent_executions = optional(number, null)",
      "job_queued_check_enabled       = optional(bool, null)",
      "down = optional(object({",
      "schedule_expression             = optional(string, null)",
      "minimum_running_time_in_minutes = optional(number, null)",
      "idle_config = optional(list(object({",
      "cron             = string",
      "timeZone         = string",
      "idleCount        = number",
      "evictionStrategy = optional(string, \"oldest_first\")",
      "pool = optional(object({",
      "config = optional(list(object({",
      "schedule_expression          = string",
      "schedule_expression_timezone = optional(string)",
      "size                         = number",
      "runner_owner         = optional(string, null)",
      "include_busy_runners = optional(bool, null)",
      "job_retry = optional(object({",
      "enabled          = optional(bool, false)",
      "delay_in_seconds = optional(number, 300)",
      "delay_backoff    = optional(number, 2)",
      "max_attempts     = optional(number, 1)",
      "memory_size                    = optional(number, 256)",
      "timeout                        = optional(number, 30)",
      "ssm = optional(object({",
      "paths = optional(object({",
      "root   = optional(string, null)",
      "tokens = optional(string, null)",
      "config = optional(string, null)",
      "parameters = optional(object({",
      "housekeeper = optional(object({",
      "artifact = optional(object({",
      "zip = optional(string, null)",
      "object_version = optional(string, null)",
      "state               = optional(string, null)",
      "tokenPath      = optional(string, null)",
      "minimumDaysOld = optional(number, null)",
      "dryRun         = optional(bool, null)",
      "observability = optional(object({",
      "logs = optional(object({",
      "retention_in_days = optional(number, null)",
      "class             = optional(string, null)",
      "tracing = optional(object({",
      "capture_http_requests = optional(bool, null)",
      "capture_error         = optional(bool, null)",
      "metrics = optional(object({",
      "namespace = optional(string, null)",
      "enable_github_app_rate_limit = optional(bool, null)",
      "enable_job_retry             = optional(bool, null)",
      "blocked_keys = optional(list(string), [])",
      "restricted_keys = optional(map(object({",
      "allowed = optional(list(string), [])",
      "denied  = optional(list(string), [])",
      "max     = optional(string, null)",
      "compute_provider = object({",
      "aws = optional(object({",
      "ec2 = optional(object({",
      "metadata_options = optional(object({",
      "instance_metadata_tags      = optional(string, \"enabled\")",
      "http_endpoint               = optional(string, \"enabled\")",
      "http_tokens                 = optional(string, \"required\")",
      "http_put_response_hop_limit = optional(number, 1)",
      "ami = optional(object({",
      "filter = optional(map(list(string)), { state = [\"available\"] })",
      "owners = optional(list(string), [\"amazon\"])",
      "id_ssm_parameter = optional(object({",
      "kms_key = optional(object({",
      "arn = string",
      "block_device_mappings = optional(list(object({",
      "delete_on_termination      = optional(bool, true)",
      "device_name                = optional(string, \"/dev/xvda\")",
      "encrypted                  = optional(bool, true)",
      "iops                       = optional(number)",
      "kms_key_id                 = optional(string)",
      "snapshot_id                = optional(string)",
      "throughput                 = optional(number)",
      "volume_initialization_rate = optional(number)",
      "volume_size                = number",
      "volume_type                = optional(string, \"gp3\")",
      "create_service_linked_role_spot = optional(bool, false)",
      "credit_specification            = optional(string, null)",
      "ebs_optimized                   = optional(bool, false)",
      "cloudwatch_agent = optional(object({",
      "config  = optional(string, null)",
      "binaries_syncer = optional(object({",
      "detailed_monitoring_enabled = optional(bool, false)",
      "ssm_enabled                 = optional(bool, false)",
      "user_data = optional(object({",
      "enabled               = optional(bool, true)",
      "template              = optional(string, null)",
      "content               = optional(string, null)",
      "pre_install           = optional(string, \"\")",
      "post_install          = optional(string, \"\")",
      "debug_logging_enabled = optional(bool, false)",
      "instance_allocation_strategy   = optional(string, \"lowest-price\")",
      "instance_max_spot_price        = optional(string, null)",
      "instance_target_capacity_type  = optional(string, \"spot\")",
      "instance_type_priorities       = optional(map(number), null)",
      "instance_types                 = list(string)",
      "additional_security_group_ids  = optional(list(string), null)",
      "managed_security_group_enabled = optional(bool, null)",
      "egress_rules = optional(list(object({",
      "instance_profile_path         = optional(string, null)",
      "key_name                      = optional(string, null)",
      "associate_public_ipv4_address = optional(bool, null)",
      "instance_profile = optional(object({",
      "name = string",
      "enable_on_demand_failover_for_errors = optional(list(string), [])",
      "scale_errors = optional(list(string), [",
      "subnet_ids = optional(list(string), null)",
      "vpc_id     = optional(string, null)",
      "cpu_options = optional(object({",
      "core_count            = optional(number)",
      "threads_per_core      = optional(number)",
      "amd_sev_snp           = optional(string)",
      "nested_virtualization = optional(string)",
      "placement = optional(object({",
      "affinity                = optional(string)",
      "availability_zone       = optional(string)",
      "group_id                = optional(string)",
      "group_name              = optional(string)",
      "host_id                 = optional(string)",
      "host_resource_group_arn = optional(string)",
      "spread_domain           = optional(string)",
      "tenancy                 = optional(string)",
      "partition_number        = optional(number)",
      "license_specifications = optional(list(object({",
      "license_configuration_arn = string",
      "use_dedicated_host = optional(bool, false)",
      "log_files = optional(list(object({",
      "log_group_name   = string",
      "prefix_log_group = bool",
      "file_path        = string",
      "log_stream_name  = string",
      "log_class        = optional(string, \"STANDARD\")",
      "tags = optional(map(string), {})",
      "matcherConfig = object({",
      "labelMatchers           = list(list(string))",
      "exactMatch              = optional(bool, false)",
      "bidirectionalLabelMatch = optional(bool, false)",
      "priority                = optional(number, 999)",
      "enableDynamicLabels     = optional(bool, false)",
      "awsDynamicLabelsPolicy = optional(object({",
      "for runner_config in values(var.runner_configs.runner_specs) :",
      "for provider_config in values(runner_config.orchestration_provider) : provider_config",
      "if provider_config != null",
      "error_message = \"Each Forge runner configuration must select exactly one non-null orchestration provider.\"",
      "variable \"tenant_configs\"",
      "ecr_registries = list(string)",
      "tags           = map(string)",
      "ec2_runner_configs = var.runner_configs.runner_specs",
      "effective_runner_users = {",
      "effective_runner_home_directories = {",
      "forge_runner_hook_job_started = {",
      "runner_hook_job_started = {",
      "effective_runner_hooks = {",
      "textencodebase64(local.effective_runner_hooks[key].job_started, \"UTF-16LE\")",
      "base64encode(local.effective_runner_hooks[key].job_started)",
      "length(runner_config.compute_provider.aws.ec2[*]) == 1",
      "length(runner_config.compute_provider.aws.ec2.ami[*]) == 1",
      "&& length(runner_config.compute_provider.aws.ec2.ami.id_ssm_parameter[*]) == 0,",
      "error_message = \"Forge EC2 runner_specs must configure a module-managed ami block; ami = null and external ami.id_ssm_parameter ownership are not supported.\"",
      "active_ec2_subnet_ids = toset(flatten([",
      "legacy_runner_labels = {",
      "runner_config.orchestration_provider.webhook.matcherConfig.labelMatchers[0]",
      "matcher_index, labels in runner_config.orchestration_provider.webhook.matcherConfig.labelMatchers",
      "!contains(local.legacy_runner_labels[key], label)",
      "ec2_default_ami_filters = {",
      "windows = { name = [\"Windows_Server-2022-English-Full-ECS_Optimized-*\"] }",
      "linux   = runner_config.runner.architecture == \"arm64\" ? { name = [\"al2023-ami-2023.*-kernel-6.*-arm64\"] } : { name = [\"al2023-ami-2023.*-kernel-6.*-x86_64\"] }",
      "osx     = runner_config.runner.architecture == \"arm64\" ? { name = [\"amzn-ec2-macos-15.*-arm64\"] } : { name = [\"amzn-ec2-macos-15.*\"] }",
      "ec2_update_runner_ami_map = {",
      "local.ec2_default_ami_filters[key],",
      "ami = runner_config.compute_provider.aws.ec2.ami == null ? null : merge(",
      "runner_config.compute_provider.aws.ec2.ami.filter,",
      "ami_filter      = local.ec2_compute_provider[key].ami.filter",
      "ami_owners      = local.ec2_compute_provider[key].ami.owners",
      "runner_ami_map = local.ec2_update_runner_ami_map",
      "key => merge(",
      "runner_config.compute_provider.aws.ec2,",
      "log_files = coalesce(runner_config.compute_provider.aws.ec2.log_files, local.forge_ec2_log_files[key])",
      "tags      = merge(var.tenant_configs.tags, runner_config.compute_provider.aws.ec2.tags)",
      "multi_runner_config = {",
      "key => merge(runner_config, {",
      "runner = merge(runner_config.runner, {",
      "iam = merge(runner_config.runner.iam, {",
      "managed_policy_arns = merge(",
      "\"forge-config-$${policy_index}\" => policy_arn",
      "forge_ec2_tags              = aws_iam_policy.ec2_tags.arn",
      "forge_runner_hooks_ssm_read = aws_iam_policy.runner_hooks_ssm_read.arn",
      "ec2 = local.ec2_compute_provider[key]",
      "runner_home    = local.effective_runner_home_directories[key]",
      "job_started   = local.runner_hook_job_started[key]",
      "runner_ssm_paths = {",
      "runner_ami_ssm_parameter_names = {",
      "root = \"$${trimsuffix(coalesce(runner_config.ssm.paths.root, \"/github-action-runners/$${var.runner_configs.prefix}\"), \"/\")}/$${key}\"",
      "multi_runner_config = {}",
      "experimental        = local.experimental_config",
      "experimental_config = {",
      "app = var.runner_configs.github_app",
      "enterprise_server = {",
      "orchestration_provider = {",
      "url = try(trimspace(var.runner_configs.ghes_url), \"\") == \"\" ? null : var.runner_configs.ghes_url",
      "artifact = {",
      "kms_key_id = aws_kms_key.github.arn",
      "level             = lower(var.runner_configs.log_level)",
      "retention_in_days = tonumber(var.runner_configs.logging_retention_in_days)",
      "runner_binaries = {",
      "multi_runner_config = local.multi_runner_config",
      "output \"ec2_runners_arn_map\"",
      "for runner_key, runner in module.runners.runners_map_v2 : runner_key => coalesce(",
      "try(local.ec2_runner_configs[runner_key].runner.iam.role.arn, null)",
      "output \"ec2_runners_ami_name_map\"",
      "data.aws_ami.runner_ami[runner_key].name",
      "output \"ec2_runners_labels_map\"",
      "output \"event_bus_name\"",
      "value       = module.runners.webhook.eventbridge.event_bus.name",
      "output \"subnet_cidr_blocks\"",
      "value       = { for id, subnet in data.aws_subnet.runner_subnet : id => subnet.cidr_block }",
      "output \"webhook_endpoint\"",
      "value       = module.runners.webhook.endpoint",
    ]
  }

  assert {
    condition     = length(output.missing_input_variables) == 0
    error_message = "Interface contract is missing input variables: ${join(", ", output.missing_input_variables)}"
  }

  assert {
    condition     = length(output.unexpected_input_variables) == 0
    error_message = "Interface contract has unexpected input variables: ${join(", ", output.unexpected_input_variables)}"
  }

  assert {
    condition     = length(output.missing_output_values) == 0
    error_message = "Interface contract is missing outputs: ${join(", ", output.missing_output_values)}"
  }

  assert {
    condition     = length(output.unexpected_output_values) == 0
    error_message = "Interface contract has unexpected outputs: ${join(", ", output.unexpected_output_values)}"
  }

  assert {
    condition     = length(output.missing_interface_literals) == 0
    error_message = "Interface contract is missing expected variable/output source lines: ${join(", ", output.missing_interface_literals)}"
  }

  assert {
    condition = (
      output.expected_input_variable_count == 4
      && output.expected_output_value_count == 6
      && output.expected_interface_literal_count == 289
    )
    error_message = "Interface contract counts must remain pinned for inputs, outputs, and source literals."
  }
}
