run "platform_ec2_deployment_contract" {
  command = plan

  module {
    source = "../../../tests/tofu/module_contract"
  }

  variables {
    module_path = "."
    expected_literals = [
      "module \"ec2_update_runner_ssm_ami\"",
      "module \"ec2_update_runner_tags\"",
      "count  = length(local.ec2_runner_configs) > 0 ? 1 : 0",
      "module \"runners\"",
      "source = \"git::https://github.com/github-aws-runners/terraform-aws-github-runner.git//modules/multi-runner?ref=microvm-multi-runner-terraform\"",
      "multi_runner_config = {}",
      "experimental_global_config = {",
      "experimental_global_config_github                 = local.experimental_config.github",
      "experimental_global_config_lambda                 = local.experimental_config.lambda",
      "experimental_global_config_orchestration_provider = local.experimental_config.orchestration_provider",
      "experimental_global_config_ssm                    = local.experimental_config.ssm",
      "experimental_global_config_observability          = local.experimental_config.observability",
      "experimental_global_config_compute_provider       = local.experimental_config.compute_provider",
      "experimental_multi_runner_config                  = local.multi_runner_config",
      "experimental_config = {",
      "app = var.runner_configs.github_app",
      "enterprise_server = {",
      "orchestration_provider = {",
      "runner_configs                  = var.runner_configs.runner_specs",
      "runner_iam_policy_arn_prefix    = \"arn:$${data.aws_partition.current.partition}:iam::$${data.aws_caller_identity.current.account_id}:policy\"",
      "runner_binaries_targets = {",
      "for target in distinct([",
      "length(try(runner_config.compute_provider.aws.ec2[*], [])) == 1",
      "try(runner_config.compute_provider.aws.ec2.binaries_syncer.enabled, null)",
      "\"$${target.os}_$${target.architecture}\" => target",
      "compute_provider_selections = {",
      "namespace = \"aws\"",
      "length(try(runner_config.compute_provider.aws.ec2[*], [])) == 1 ? \"ec2\" :",
      "length(try(runner_config.compute_provider.aws.microvm[*], [])) == 1 ? \"microvm\" : null",
      "ec2_runner_configs = {",
      "microvm_runner_configs = {",
      "if length(try(runner_config.compute_provider.aws.ec2[*], [])) == 1",
      "if length(try(runner_config.compute_provider.aws.microvm[*], [])) == 1",
      "runner_config.compute_provider.aws.ec2,",
      "aws = merge(runner_config.compute_provider.aws, {",
      "ec2 = try(local.ec2_compute_provider[key], null)",
      "microvm = optional(object({",
      "image_arn                   = optional(string, null)",
      "lambda_artifacts = optional(object({",
      "control_plane_zip = optional(string, null)",
      "webhook_zip       = optional(string, null)",
      "control_plane_lambda_zip = try(coalesce(",
      "webhook_lambda_zip = try(coalesce(",
      "boot_time_in_minutes = optional(number, null)",
      "ephemeral            = optional(bool, null)",
      "jit_config_enabled   = optional(bool, null)",
      "maximum_count        = optional(number, null)",
      "scale = optional(object({",
      "up = optional(object({",
      "down = optional(object({",
      "runner_config.orchestration_provider.webhook.matcherConfig.labelMatchers[0]",
      "matcher_index, labels in runner_config.orchestration_provider.webhook.matcherConfig.labelMatchers",
      "kms_key_id = aws_kms_key.github.arn",
      "selections = local.compute_provider_selections",
      "targets = local.runner_binaries_targets",
      "multi_runner_config = local.multi_runner_config",
      "resource \"aws_cloudwatch_log_group\" \"webhook_api_gateway_access\"",
      "resource \"aws_kms_key\" \"github\"",
      "resource \"aws_kms_alias\" \"github\"",
      "resource \"aws_ssm_parameter\" \"hook_job_started\"",
      "resource \"aws_ssm_parameter\" \"hook_job_completed\"",
      "runner_ssm_paths = {",
      "root = \"$${trimsuffix(coalesce(runner_config.ssm.paths.root, \"/github-action-runners/$${var.runner_configs.prefix}\"), \"/\")}/$${key}\"",
      "runner_ami_ssm_parameter_names = {",
      "key => \"$${paths.root}/$${paths.config}/ami_id\"",
      "resource \"aws_iam_policy\" \"runner_hooks_ssm_read\"",
      "resource \"aws_iam_policy\" \"ec2_tags\"",
      "forge_ec2_tags              = \"$${local.runner_iam_policy_arn_prefix}$${aws_iam_policy.ec2_tags[0].path}$${aws_iam_policy.ec2_tags[0].name}\"",
      "forge_runner_hooks_ssm_read = \"$${local.runner_iam_policy_arn_prefix}$${aws_iam_policy.runner_hooks_ssm_read[0].path}$${aws_iam_policy.runner_hooks_ssm_read[0].name}\"",
      "count       = length(local.ec2_runner_configs) > 0 ? 1 : 0",
      "resource \"aws_security_group\" \"gh_runner_lambda_egress\"",
      "data \"aws_ssm_parameter\" \"ami_id\"",
      "data \"aws_ami\" \"runner_ami\"",
      "data \"aws_caller_identity\" \"current\"",
      "data \"aws_partition\" \"current\"",
      "data \"aws_subnet\" \"runner_subnet\"",
      "data \"external\" \"download_lambdas\"",
      "program = [\"bash\", \"$${path.module}/scripts/download_lambdas.sh\", \"/tmp/$${var.runner_configs.prefix}/v7.10.1/\", \"v7.10.1\", \"github-aws-runners/terraform-aws-github-runner\"]",
      "|| try(var.runner_configs.lambda_artifacts.control_plane_zip, null) == null",
      "|| try(var.runner_configs.lambda_artifacts.webhook_zip, null) == null",
      "data.external.download_lambdas[0].result.path",
      "data \"aws_iam_policy_document\" \"runner_hooks_ssm_read\"",
      "data \"aws_iam_policy_document\" \"ec2_tags\"",
      "output \"webhook_endpoint\"",
      "output \"ec2_runners_arn_map\"",
      "output \"ec2_runners_ami_name_map\"",
      "output \"ec2_runners_labels_map\"",
      "output \"runners_arn_map\"",
      "output \"runners_labels_map\"",
      "output \"microvm_runners_arn_map\"",
      "output \"microvm_runners_labels_map\"",
      "output \"microvm_runners_map\"",
      "output \"subnet_cidr_blocks\"",
      "output \"event_bus_name\"",
      "from = aws_iam_policy.ec2_tags",
      "to   = aws_iam_policy.ec2_tags[0]",
      "from = aws_iam_policy.runner_hooks_ssm_read",
      "to   = aws_iam_policy.runner_hooks_ssm_read[0]",
      "from = module.ec2_update_runner_ssm_ami",
      "to   = module.ec2_update_runner_ssm_ami[0]",
      "from = module.ec2_update_runner_tags",
      "to   = module.ec2_update_runner_tags[0]",
    ]
  }

  assert {
    condition     = length(output.missing_expected_literals) == 0
    error_message = "Module contract is missing expected literals: ${join(", ", output.missing_expected_literals)}"
  }

  assert {
    condition     = output.expected_literal_count > 0
    error_message = "Module contract must pin at least one module-specific literal."
  }
}
