run "platform_forge_runners_interface_contract" {
  command = plan

  module {
    source = "../../../tests/tofu/module_interface_contract"
  }

  variables {
    module_path = "."
    expected_input_variables = [
      "arc_deployment_specs",
      "aws_profile",
      "aws_region",
      "default_tags",
      "deployment_config",
      "ec2_deployment_specs",
      "github_webhook_relay",
      "log_level",
      "logging_retention_in_days",
      "tags",
    ]
    expected_output_values = [
      "forge_core",
      "forge_github_actions_job_logs",
      "forge_github_app",
      "forge_runners",
      "forge_webhook_relay",
    ]
    expected_interface_literals = [
      "variable \"arc_deployment_specs\"",
      "type = object({",
      "cluster_name    = string",
      "migrate_cluster = optional(bool, false)",
      "runner_specs = map(object({",
      "runner_size = object({",
      "max_runners = number",
      "min_runners = number",
      "scale_set_name   = string",
      "scale_set_type   = string",
      "scale_set_labels = list(string)",
      "container_images = optional(object({",
      "actions_runner = optional(string, \"ghcr.io/actions/actions-runner:latest\")",
      "busybox        = optional(string, \"public.ecr.aws/docker/library/busybox:stable\")",
      "dind_rootless  = optional(string, \"public.ecr.aws/docker/library/docker:dind-rootless\")",
      "}), {})",
      "container_limits_cpu         = string",
      "container_limits_memory      = string",
      "container_requests_cpu       = string",
      "container_requests_memory    = string",
      "volume_requests_storage_size = string",
      "volume_requests_storage_type = string",
      "}))",
      "description = <<-EOT",
      "Deployment configuration for Azure Container Apps (ARC) runners.",
      "Top-level fields:",
      "- cluster_name   : Name of the EKS cluster used for ARC runners.",
      "- migrate_cluster: Optional flag to indicate a one-time migration or",
      "blue/green cutover of the ARC runner cluster.",
      "- runner_specs   : Map of ARC runner pool keys to their sizing and",
      "container resource settings.",
      "runner_specs[*] object fields:",
      "- runner_size.max_runners: Maximum concurrent ARC runners for this pool.",
      "- runner_size.min_runners: Minimum number of warm runners.",
      "- scale_set_name         : Logical name for the scale set / pool.",
      "- scale_set_type         : Backing type for the scale set (for example,",
      "kubernetes or containerapp, depending on integration).",
      "- scale_set_labels       : GitHub runner labels advertised by this ARC",
      "scale set.",
      "- container_images            : Container images used by the ARC runner,",
      "sidecars, and DinD containers.",
      "- container_limits_cpu        : CPU limit for the runner container.",
      "- container_limits_memory     : Memory limit for the runner container.",
      "- container_requests_cpu      : CPU request (baseline reservation).",
      "- container_requests_memory   : Memory request (baseline reservation).",
      "- volume_requests_storage_size: Size of attached storage for the runner.",
      "- volume_requests_storage_type: Storage class or type for attached volume.",
      "EOT",
      "variable \"aws_profile\"",
      "type        = string",
      "description = \"AWS profile to use.\"",
      "variable \"aws_region\"",
      "description = \"AWS region where Forge runners and supporting infrastructure are deployed.\"",
      "variable \"default_tags\"",
      "type        = map(string)",
      "description = \"A map of tags to apply to resources.\"",
      "variable \"deployment_config\"",
      "deployment_prefix = string",
      "secret_suffix     = string",
      "env               = string",
      "github_app = object({",
      "id              = string",
      "client_id       = string",
      "installation_id = string",
      "name            = string",
      "github = object({",
      "ghes_org             = string",
      "ghes_url             = string",
      "repository_selection = string",
      "runner_group_name    = string",
      "tenant = object({",
      "name                         = string",
      "iam_roles_to_assume          = optional(list(string), [])",
      "ecr_registries               = optional(list(string), [])",
      "github_logs_reader_role_arns = optional(list(string), [])",
      "validation {",
      "condition     = contains([\"all\", \"selected\"], var.deployment_config.github.repository_selection)",
      "error_message = \"repository_selection must be 'all' or 'selected'.\"",
      "condition     = trimspace(var.deployment_config.github.ghes_org) != \"\"",
      "error_message = \"ghes_org must be non-empty.\"",
      "High-level deployment configuration for a Forge runner installation.",
      "- deployment_prefix: Prefix used when naming resources (for example,",
      "log groups, KMS keys, and SSM parameters).",
      "- env              : Logical environment name (for example, dev, stage,",
      "prod). Used for tagging and dashboards.",
      "github_app object:",
      "- id             : Numeric GitHub App ID.",
      "- client_id      : OAuth client ID for the app.",
      "- installation_id: GitHub App installation ID for this tenant.",
      "- name           : GitHub App name, used to build URLs and logs.",
      "github object:",
      "- ghes_org            : GitHub organization that owns the repos where",
      "runners will be used.",
      "- ghes_url            : GitHub.com or GHES base URL. Empty string implies",
      "public github.com.",
      "- repository_selection: Scope for runners (all or selected repositories).",
      "- runner_group_name   : GitHub runner group to attach new runners to.",
      "tenant object:",
      "- name                        : Tenant identifier used in naming and",
      "tagging.",
      "- iam_roles_to_assume         : Optional list of IAM role ARNs that",
      "runners are allowed to assume for workload execution.",
      "- ecr_registries              : Optional list of ECR registry URLs that",
      "runners may need to pull images from.",
      "- github_logs_reader_role_arns: Optional list of IAM roles that can read",
      "GitHub Actions logs for this tenant.",
      "variable \"ec2_deployment_specs\"",
      "lambda_subnet_ids = list(string)",
      "subnet_ids        = list(string)",
      "lambda_vpc_id     = string",
      "vpc_id            = string",
      "runner_labels         = list(string)",
      "runner_os             = string",
      "runner_architecture   = string",
      "extra_labels          = list(string)",
      "enable_dynamic_labels = optional(bool, false)",
      "aws_dynamic_labels_policy = optional(object({",
      "blocked_keys = optional(list(string), [])",
      "restricted_keys = optional(map(object({",
      "allowed = optional(list(string), [])",
      "denied  = optional(list(string), [])",
      "max     = optional(string, null)",
      "lambda_event_source_mapping_batch_size                         = optional(number, 10)",
      "lambda_event_source_mapping_maximum_batching_window_in_seconds = optional(number, 0)",
      "redrive_build_queue = optional(object({",
      "enabled         = optional(bool, true)",
      "maxReceiveCount = optional(number, 10)",
      "max_instances = number",
      "min_run_time  = number",
      "pool_config = list(object({",
      "size                         = number",
      "schedule_expression          = string",
      "schedule_expression_timezone = string",
      "runner_user = string",
      "compute_provider = object({",
      "ec2 = optional(object({",
      "ami_filter = object({",
      "name  = list(string)",
      "state = list(string)",
      "ami_kms_key_arn = string",
      "ami_owners      = list(string)",
      "instance_types  = list(string)",
      "license_specifications = optional(list(object({",
      "license_configuration_arn = string",
      "placement = optional(object({",
      "affinity                = optional(string)",
      "availability_zone       = optional(string)",
      "group_id                = optional(string)",
      "group_name              = optional(string)",
      "host_id                 = optional(string)",
      "host_resource_group_arn = optional(string)",
      "spread_domain           = optional(string)",
      "tenancy                 = optional(string)",
      "partition_number        = optional(number)",
      "use_dedicated_host            = optional(bool, false)",
      "enable_userdata               = bool",
      "instance_target_capacity_type = string",
      "vpc_id                        = optional(string, null)",
      "subnet_ids                    = optional(list(string), null)",
      "block_device_mappings = list(object({",
      "delete_on_termination      = bool",
      "device_name                = string",
      "encrypted                  = bool",
      "iops                       = number",
      "kms_key_id                 = string",
      "snapshot_id                = string",
      "throughput                 = number",
      "volume_initialization_rate = optional(number)",
      "volume_size                = number",
      "volume_type                = string",
      "scale_errors                  = optional(list(string), [])",
      "microvm = optional(object({",
      "image_identifier          = string",
      "image_version             = optional(string, null)",
      "egress_network_connectors = optional(list(string), [])",
      "idle_policy = optional(object({",
      "max_idle_duration_seconds  = number",
      "suspended_duration_seconds = number",
      "auto_resume_enabled        = bool",
      "logging = optional(object({",
      "cloud_watch = optional(object({",
      "log_group  = optional(string, null)",
      "log_stream = optional(string, null)",
      "disabled = optional(bool, false)",
      "run_hook_payload            = optional(string, null)",
      "maximum_duration_in_seconds = optional(number, null)",
      "environment_variables       = optional(map(string), {})",
      "tags                        = optional(map(string), {})",
      "iam = optional(object({",
      "resource_arns = optional(list(string), [\"*\"])",
      "actions = optional(object({",
      "scale_up   = optional(list(string), null)",
      "scale_down = optional(list(string), null)",
      "additional_policy_json = optional(object({",
      "scale_up = optional(string, null)",
      "managed_policy_arns = optional(object({",
      "pool     = optional(string, null)",
      "for runner_config in values(var.ec2_deployment_specs.runner_specs) :",
      "for provider_type, provider_config in runner_config.compute_provider : provider_type",
      "if provider_config != null",
      "error_message = \"Each runner_specs entry must configure exactly one compute provider: ec2 or microvm.\"",
      "Compute deployment configuration for GitHub Actions runners.",
      "- lambda_subnet_ids: Subnets where runner-related lambdas execute.",
      "These can be more permissive than the runner subnets.",
      "- subnet_ids       : Default subnets for compute providers that use the VPC.",
      "- vpc_id           : VPC that contains both runner and lambda subnets.",
      "- runner_specs     : Map of provider-aware runner lanes.",
      "- runner_labels   : Base GitHub labels applied to jobs for this pool.",
      "- runner_os       : Runner operating system (for example, linux).",
      "- redrive_build_queue: Optional dead-letter queue redrive configuration.",
      "- compute_provider: Exactly one typed provider block: ec2 or microvm.",
      "compute_provider.ec2 fields:",
      "- scale_errors    : Retryable EC2 scale-up error codes.",
      "compute_provider.microvm fields:",
      "- image_identifier: ARN or ID of the Lambda MicroVM image.",
      "- iam             : Optional MicroVM control-plane IAM overrides.",
      "variable \"github_webhook_relay\"",
      "Configuration for the (optional) webhook relay source module.",
      "If enabled=true we provision the API Gateway + source EventBridge forwarding rule.",
      "destination_event_bus_name must already exist or be created in the destination account (or via the destination submodule run there).",
      "enabled                     = bool",
      "destination_account_id      = optional(string)",
      "destination_event_bus_name  = optional(string)",
      "destination_region          = optional(string)",
      "destination_reader_role_arn = optional(string)",
      "default = {",
      "enabled                     = false",
      "destination_account_id      = \"\"",
      "destination_event_bus_name  = \"\"",
      "destination_region          = \"\"",
      "destination_reader_role_arn = \"\"",
      "variable \"log_level\"",
      "description = \"Log level for application logging (e.g., INFO, DEBUG, WARN, ERROR)\"",
      "variable \"logging_retention_in_days\"",
      "description = \"Logging retention period in days.\"",
      "variable \"tags\"",
      "output \"forge_core\"",
      "description = \"Core tenant-level metadata (non-sensitive).\"",
      "value = {",
      "tenant            = var.deployment_config.tenant",
      "runner_group_name = var.deployment_config.github.runner_group_name",
      "output \"forge_github_actions_job_logs\"",
      "description = \"GitHub Actions job log archival resources.\"",
      "bucket_arn               = try(module.github_actions_job_logs[0].s3_bucket_arn, null)",
      "bucket_kms_key_arn       = try(module.github_actions_job_logs[0].s3_bucket_kms_key_arn, null)",
      "sqs                      = try(module.github_actions_job_logs[0].sqs, null)",
      "internal_reader_role_arn = try(module.github_actions_job_logs[0].internal_s3_reader_role_arn, null)",
      "output \"forge_github_app\"",
      "description = \"GitHub App related outputs.\"",
      "installation_url = local.github_app_installation",
      "installation_id  = var.deployment_config.github_app.installation_id",
      "name             = var.deployment_config.github_app.name",
      "sensitive = true",
      "output \"forge_runners\"",
      "description = \"Combined compute-provider and ARC runner outputs.\"",
      "compute = {",
      "runners_arn_map = try(module.ec2_runners[0].runners_arn_map, {})",
      "runner_labels   = try(module.ec2_runners[0].runners_labels_map, {})",
      "ec2 = {",
      "runners_arn_map    = try(module.ec2_runners[0].ec2_runners_arn_map, {})",
      "ami_name_map       = try(module.ec2_runners[0].ec2_runners_ami_name_map, {})",
      "subnet_cidr_blocks = try(module.ec2_runners[0].subnet_cidr_blocks, [])",
      "runner_labels      = try(module.ec2_runners[0].ec2_runners_labels_map, {})",
      "microvm = {",
      "runners_arn_map = try(module.ec2_runners[0].microvm_runners_arn_map, {})",
      "runners         = try(module.ec2_runners[0].microvm_runners_map, {})",
      "runner_labels   = try(module.ec2_runners[0].microvm_runners_labels_map, {})",
      "arc = {",
      "cluster_name       = try(module.arc_runners.arc_cluster_name, {})",
      "runners_arn_map    = try(module.arc_runners.arc_runners_arn_map, {})",
      "subnet_cidr_blocks = try(module.arc_runners.subnet_cidr_blocks, [])",
      "runner_labels      = try(module.arc_runners.arc_runners_labels_map, {})",
      "output \"forge_webhook_relay\"",
      "description = \"Webhook relay integration outputs.\"",
      "source_secret_arn      = try(module.github_webhook_relay[0].source_secret_arn, null)",
      "source_secret_role_arn = try(module.github_webhook_relay[0].source_secret_role_arn, null)",
      "source_secret_region   = try(module.github_webhook_relay[0].source_secret_region, null)",
    ]
  }

  assert {
    condition     = length(output.missing_input_variables) == 0
    error_message = "Interface contract is missing input variables: ${join(", ", output.missing_input_variables)}"
  }

  assert {
    condition     = length(output.unexpected_input_variables) == 0
    error_message = "Interface contract has unexpected input variables: ${join(", ", output.unexpected_input_variables)}"
  }

  assert {
    condition     = length(output.missing_output_values) == 0
    error_message = "Interface contract is missing outputs: ${join(", ", output.missing_output_values)}"
  }

  assert {
    condition     = length(output.unexpected_output_values) == 0
    error_message = "Interface contract has unexpected outputs: ${join(", ", output.unexpected_output_values)}"
  }

  assert {
    condition     = length(output.missing_interface_literals) == 0
    error_message = "Interface contract is missing expected variable/output source lines: ${join(", ", output.missing_interface_literals)}"
  }

  assert {
    condition = (
      output.expected_input_variable_count == 10
      && output.expected_output_value_count == 5
      && output.expected_interface_literal_count == 277
    )
    error_message = "Interface contract counts must remain pinned for inputs, outputs, and source literals."
  }
}
